In [ ]:
import numpy as np

In [ ]:
q = np.arange(8,-1,-1) #одномерный массив от 8 до -1 (правая граница не входит как мы помним) с шагом -1!
q

array([8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
#1

n = int(input())

x = np.arange(0,n)#создание одномерного массива от 0 до n
rev_x = x[::-1]#разворот этого массива
rev_x

6


array([5, 4, 3, 2, 1, 0])

In [ ]:
#2

w = np.diag(rev_x, k=0) #метод DIAG либо извлекает к-тую диагональ из 2-мерного объекта, либо строит 2-мерный объект, располагая переданный в кач-ве аргумента одномерный по к-той диагонали
w

array([[5, 0, 0, 0, 0, 0],
       [0, 4, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0]])

In [ ]:
np.trace(w,0) #возвращает ссумму значений по диагонали. Принимает много разных параметров, в частности, выбрать диагональ(по аналогии с к-той диагональю из примера выше, указывается просто через запятую после имени матрицы)

15

#3

4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [ ]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )#массив из  коэфф из левой

In [ ]:
b = np.array( [4, 12, -3] )# массив из коэфф из правой

In [ ]:
from numpy import linalg

In [ ]:
linalg.solve(a, b)#решение с помощью метода solve. Получаем x, y, z

array([ 0.46666667,  3.84444444, -5.55555556])

In [ ]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )#проверка решения

True

In [ ]:
#4

users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 1, 2, 0, 0, 0],#редактировал строку
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [ ]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [ ]:
def get_cosine(users_stats,next_user_stats):

  nus_lenght = np.linalg.norm(next_user_stats)#длина вектора нового пользователя

  cos_list = []

  for i in users_stats:
    i_lenght = np.linalg.norm(i)#вычисление длины вектора пользователя из матрицы в каждом проходе цикла
    cos_list.append(np.dot(i, next_user_stats) / (i_lenght * nus_lenght))#также в каждом проходе цикла вычисление косинусного сходства 
    
  return cos_list.index(max(cos_list))+1 #функция возвращает индекс максимального значения списка + 1, иначе они с 0 начинаются

get_cosine(users_stats,next_user_stats)

5

In [ ]:
def get_cosine_dict(users_stats,next_user_stats):#решение через ключи словаря

  nus_lenght_dict = np.linalg.norm(next_user_stats)#отдельно посчитал длину вектора нового пользователя

  cos_dict = {}#создание пустого словаря

  for y, i in enumerate(users_stats):#цикл перебирает матрицу, плюс еще enumerate добавился
    i_lenght = np.linalg.norm(i)#длина вектора на каждом этапе цикла
    cos_dict[y+1] = (np.dot(i, next_user_stats) / (i_lenght * nus_lenght_dict))#создание словаря, где ключом становится значение enumrate(+1 чтобы с 0 не начинать), а значением косинусное сходство между новым вектором и вектром, который в текущюю итерацию цикла попал
  return max(cos_dict, key=cos_dict.get)#возвращает ключ, который соответствует максимальному значению словаря. Для этого в функцию МАХ передаем дополнительный аргумент KEY

get_cosine_dict(users_stats,next_user_stats)

5